SELECT b.AUTHOR_ID, a.AUTHOR_NAME, b.CATEGORY, SUM(sb.SALES * b.PRICE) AS TOTAL_SALES
FROM BOOK b
JOIN AUTHOR a ON b.AUTHOR_ID = a.AUTHOR_ID
JOIN BOOK_SALES sb ON b.BOOK_ID = sb.BOOK_ID
WHERE DATE_FORMAT(SALES_DATE, '%Y-%m') = '2022-01'
GROUP BY b.AUTHOR_ID, b.CATEGORY
ORDER BY b.AUTHOR_ID ASC, b.CATEGORY DESC;

# BOOK, AUTHOR, BOOK_SALES에서
# '2022-01'의 '판매' 데이터의
# 저자 별, 카테고리 별 매출액(TOTAL_SALES = 판매량 * 판매가)
# 저자ID, 저자명, 카테고리, 매출액 출력
# 저자ID ASC, 카테고리 DESC