SELECT ii.ITEM_ID, ii.ITEM_NAME
FROM ITEM_INFO ii
JOIN ITEM_TREE it ON ii.ITEM_ID = it.ITEM_ID
WHERE it.PARENT_ITEM_ID IS NULL
ORDER BY ITEM_ID ASC;

# ITEM_INFO, ITEM_TREE에서
# ROOT 아이템의
# ID, 아이템명 출력
# ID ASC