SELECT ROUND(AVG(DAILY_FEE)) AS AVERAGE_FEE
FROM CAR_RENTAL_COMPANY_CAR
WHERE CAR_TYPE = 'SUV'
# CAR_RENTAL_COMPANY_CAR 테이블
# 자동차 종류 = 'SUV'들의
# 평균 일일 대여 요금 출력
# 출력 형식: 소수 첫 번째 자리에서 반올림, 컬럼명은 AVERAGE_FEE