SELECT ii.ITEM_ID, ii.ITEM_NAME, ii.RARITY
FROM ITEM_INFO ii
LEFT JOIN ITEM_TREE it ON ii.ITEM_ID = it.PARENT_ITEM_ID
WHERE it.PARENT_ITEM_ID IS NULL
ORDER BY ii.ITEM_ID DESC;

# ITEM_INFO, ITEM_TREE에서
# 더 이상 업그레이드할 수 없는 아이템의
# ID, 아이템명, 아이템의 희귀도 출력
# ID DESC