SELECT p.PRODUCT_CODE, SUM(PRICE * SALES_AMOUNT) AS SALES
FROM PRODUCT p
JOIN OFFLINE_SALE os
ON p.PRODUCT_ID = os.PRODUCT_ID
GROUP BY p.PRODUCT_CODE
ORDER BY SUM(PRICE * SALES_AMOUNT) DESC, p.PRODUCT_CODE;