# ONLINE_SALE, OFFLINE_SALE 테이블에서
# '2022-03'의 오프라인/온라인 상품 판매 데이터의
# 판매 날짜, 상품ID, 유저ID, 판매량 출력
# OFFLINE_SALE 테이블의 판매 데이터의 USER_ID 값은 NULL로 표시
# 판매일을 기준으로 오름차순
# if) 판매일이 같다면 상품ID를 기준으로 오름차순
# 상품ID도 같다면 유저ID를 기준으로 오름차순 정렬

# 교차합

SELECT DATE_FORMAT(SALES_DATE, '%Y-%m-%d') AS SALES_DATE, PRODUCT_ID, USER_ID, SALES_AMOUNT
FROM ONLINE_SALE
WHERE DATE_FORMAT(SALES_DATE, '%Y-%m') = '2022-03'
UNION ALL
SELECT DATE_FORMAT(SALES_DATE, '%Y-%m-%d') AS SALES_DATE, PRODUCT_ID, NULL AS USER_ID, SALES_AMOUNT
FROM OFFLINE_SALE
WHERE DATE_FORMAT(SALES_DATE, '%Y-%m') = '2022-03'
ORDER BY SALES_DATE, PRODUCT_ID, USER_ID;