SELECT DATE_FORMAT(SALES_DATE, '%Y-%m-%d') AS SALES_DATE, PRODUCT_ID, USER_ID, SALES_AMOUNT
FROM ONLINE_SALE
WHERE DATE_FORMAT(SALES_DATE, '%Y-%m') = '2022-03'

UNION ALL

SELECT DATE_FORMAT(SALES_DATE, '%Y-%m-%d') AS SALES_DATE, PRODUCT_ID, NULL AS USER_ID, SALES_AMOUNT
FROM OFFLINE_SALE
WHERE DATE_FORMAT(SALES_DATE, '%Y-%m') = '2022-03'

ORDER BY SALES_DATE ASC, PRODUCT_ID, USER_ID ASC;

# ONLINE_SALE, OFFLINE_SALE에서
# '2022-03'의 오프라인/온라인 상품 판매 데이터의
# 판매 날짜, 상품ID, 유저ID, 판매량 출력
# OFFLINE_SALE의 USER_ID는 'NULL'로 표시
# 판매일 ASC, 상품ID ASC, 유저ID ASC