SELECT FOOD_TYPE, REST_ID, REST_NAME, FAVORITES
FROM REST_INFO
GROUP BY FOOD_TYPE
HAVING MAX(FAVORITES) = (
    SELECT MAX(FAVORITES)
    FROM REST_INFO r2
    WHERE r2.REST_ID = REST_INFO.REST_ID
)
ORDER BY FOOD_TYPE DESC;

# REST_INFO에서
# 음식종류별로
# 즐겨찾기수가 가장 많은 식당의
# 음식 종류, ID, 식당 이름, 즐겨찾기수 조회
# 음식 종류 DESC