WITH MostRest AS (
    SELECT FOOD_TYPE, REST_ID, REST_NAME, FAVORITES,
           ROW_NUMBER() OVER (PARTITION BY FOOD_TYPE ORDER BY FAVORITES DESC) AS rn
    FROM REST_INFO
)
SELECT FOOD_TYPE, REST_ID, REST_NAME, FAVORITES
FROM MostRest
WHERE rn = 1
ORDER BY FOOD_TYPE DESC;

# REST_INFO에서
# 음식종류별로
# 즐겨찾기수가 가장 많은 식당의
# 음식 종류, ID, 식당 이름, 즐겨찾기수 조회
# 음식 종류 DESC