SELECT RI.FOOD_TYPE, RI.REST_ID, RI.REST_NAME, RI.FAVORITES
FROM REST_INFO RI
WHERE RI.FAVORITES = (
    SELECT MAX(FAVORITES)
    FROM REST_INFO
    WHERE FOOD_TYPE = RI.FOOD_TYPE
)
ORDER BY RI.FOOD_TYPE DESC;

# REST_INFO에서
# '음식종류별'로
# '즐겨찾기수'가 '가장 많은' 식당의
# 음식 종류, ID, 식당 이름, 즐겨찾기수 조회
# 음식 종류 DESC