SELECT WAREHOUSE_ID, WAREHOUSE_NAME, ADDRESS, IFNULL(FREEZER_YN, 'N') AS 'FREEZER_YN'
FROM FOOD_WAREHOUSE
WHERE ADDRESS LIKE '경기도%'
ORDER BY WAREHOUSE_ID ASC;

# FOOD_WAREHOUSE에서
# '경기도'에 위치한 창고의
# ID, 이름, 주소, 냉동시설 여부 조회
# if) 냉동시설 == NULL -> 'N'으로 출력
# ID ASC