SELECT fp.PRODUCT_ID, fp.PRODUCT_NAME, SUM(fp.PRICE * fo.AMOUNT) AS TOTAL_SALES
FROM FOOD_PRODUCT fp
JOIN FOOD_ORDER fo ON fp.PRODUCT_ID = fo.PRODUCT_ID
WHERE DATE_FORMAT(fo.PRODUCE_DATE, '%Y-%m') = '2022-05'
GROUP BY fp.PRODUCT_NAME
ORDER BY TOTAL_SALES DESC, fp.PRODUCT_ID;
# FOOD_PRODUCT, FOOD_ORDER에서
# 생산일자가 '2022-05'인 식품들의
# 식품ID, 식품 이름, 총매출 조회
# 총매출 DESC, 식품 ID ASC;