SELECT MEMBER_ID, MEMBER_NAME, GENDER, DATE_FORMAT(DATE_OF_BIRTH, "%Y-%m-%d") AS DATE_OF_BIRTH
FROM MEMBER_PROFILE
WHERE MONTH(DATE_OF_BIRTH) = 3 AND GENDER = 'W' AND TLNO IS NOT NULL
ORDER BY MEMBER_ID ASC;

# MEMBER_PROFILE 테이블에서
# 생일이 '3월'인 '여성'회원의
# ID, 이름, 성별, 생년월인 조회
# if) 전화번호 == NULL 출력x
# 회원ID 기준 ASC
# 날짜 출력형식 확인