SELECT MEMBER_ID, MEMBER_NAME, GENDER, DATE_FORMAT(DATE_OF_BIRTH, '%Y-%m-%d') AS DATE_OF_BIRTH
FROM MEMBER_PROFILE
WHERE DATE_FORMAT(DATE_OF_BIRTH, '%m') = '03' AND GENDER = 'W' AND TLNO IS NOT NULL
ORDER BY MEMBER_ID;
# MEMBER_PROFILE 테이블에서
# 생일 = '3월' && 여성
# ID, 이름, 성별, 생년월일을 조회
# IF 전화번호 = NULL => 출력 x
# 회원 ID ASC