SELECT USER_ID, NICKNAME, SUM(PRICE) AS TOTAL_SALES
FROM USED_GOODS_BOARD ugb
JOIN USED_GOODS_USER ugu ON ugb.WRITER_ID = ugu.USER_ID
WHERE STATUS = 'DONE'
GROUP BY USER_ID, NICKNAME
HAVING SUM(PRICE) >= 700000
ORDER BY TOTAL_SALES ASC;

# USED_GOODS_BOARD, USED_GOODS_USER에서
# STATUS == 'DONE' && 가격 >= 70만원인 사람의
# 회원ID, 닉네임, 총거래금액 조회
# 총거래금액 ASC