SELECT MONTH(START_DATE) AS MONTH, CAR_ID, COUNT(HISTORY_ID) AS RECORDS
FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
WHERE START_DATE BETWEEN '2022-08-01' AND '2022-10-31'
AND CAR_ID IN (
    SELECT CAR_ID
    FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
    WHERE START_DATE BETWEEN '2022-08-01' AND '2022-10-31'
    GROUP BY CAR_ID
    HAVING COUNT(HISTORY_ID) > 4
)
GROUP BY MONTH, CAR_ID
HAVING RECORDS > 0
ORDER BY MONTH, CAR_ID DESC;

# CAR_RENTAL_COMPANY_RENTAL_HISTORY에서
# 대여 시작일을 기준으로 '2022-08' ~ '2022-10'까지 총 대여 횟수가 5회 이상인 자동차들의
# 해당 기간 동안의 월별 자동차ID 별 총 대여 횟수 출력
# 월 ASC, 자동차ID DESC
# if) 특정 월의 총 대여 횟수 == '0' -> 결과에서 제외