# SKILLCODES, DEVELOPERS 테이블에서
# Python, C# 스킬을 가진 개발자의
# 개발자 ID, 이메일, 이름, 성 조회
# ID를 기준으로 오름차순 정렬
SELECT ID, EMAIL, FIRST_NAME, LAST_NAME
FROM DEVELOPERS
WHERE SKILL_CODE & (SELECT CODE FROM SKILLCODES WHERE NAME = 'Python')
    OR SKILL_CODE & (SELECT CODE FROM SKILLCODES WHERE NAME = 'C#')
ORDER BY ID;