# FISH_INFO 테이블에서
# 잡은 'BASS'와 'SNAPPER'의 수를 출려겨
# FISH_COUNT
SELECT COUNT(ID) AS FISH_COUNT
FROM FISH_INFO fi, FISH_NAME_INFO fni
WHERE fi.FISH_TYPE = fni.FISH_TYPE AND fni.FISH_NAME IN ('BASS', "SNAPPER");