SELECT COUNT(*) AS FISH_COUNT
FROM FISH_INFO fi
JOIN FISH_NAME_INFO fni
ON fi.FISH_TYPE = fni.FISH_TYPE
WHERE FISH_NAME = 'BASS' OR FISH_NAME = 'SNAPPER';

# FISH_INFO, FISH_NAME_INFO에서
# BASS, SNAPPER의 수 출력 -> FISH_COUNT