SELECT fh.FLAVOR
FROM FIRST_HALF fh
INNER JOIN ICECREAM_INFO ii
ON fh.FLAVOR = ii.FLAVOR
WHERE TOTAL_ORDER > 3000 AND ii.INGREDIENT_TYPE = 'fruit_based'
ORDER BY TOTAL_ORDER DESC;

# 상반기 아이스크림의
# 총주문량 > 3,000 && 주성분 == '과일'인 아이스크림 맛을
# 총주문량 DESC