SELECT BOOK_ID, DATE_FORMAT(PUBLISHED_DATE, '%Y-%m-%d') AS PUBLISHED_DATE
FROM BOOK
WHERE YEAR(PUBLISHED_DATE) = '2021' and CATEGORY = '인문'
ORDER BY BOOK_ID, PUBLISHED_DATE;
# BOOK에서
# 출판년도 = '2021' && 카테고리 = '인문'
# 도서 ID ASC, 출판일 ASC