SELECT INGREDIENT_TYPE, SUM(TOTAL_ORDER) AS TOTAL_ORDER
FROM FIRST_HALF fh
JOIN ICECREAM_INFO ii ON fh.FLAVOR = ii.FLAVOR
GROUP BY INGREDIENT_TYPE
ORDER BY TOTAL_ORDER ASC;

# FIRST_HALF, ICECREAM_INFO에서
# 각 아이스크림 성분 타입, 성분 타입에 대한 아이스크림의 총주문량(TOTAL_ORDER) 조회
# 총주문량 ASC