SELECT CATEGORY, SUM(SALES) AS TOTAL_SALES
FROM BOOK b
JOIN BOOK_SALES bs ON b.BOOK_ID = bs.BOOK_ID
WHERE DATE_FORMAT(SALES_DATE, '%Y-%m') = '2022-01'
GROUP BY CATEGORY
ORDER BY CATEGORY ASC;

# BOOK, BOOK_SALES에서
# '2022-01'의 카테고리 별 도서 판매량 합산
# 카테고리, 총 판매량 출력
# 카테고리명 ASC